spring.main.allow-circular-references = true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.config.import: configserver:http://localhost:8888

server.port=${application.nosliw-datasource.port}
spring.application.name=${application.nosliw-datasource.name}


taskinterface.path = file:///C:/Mywork/CoreProjects/ApplicationData/serviceinterface

