spring.main.allow-circular-references = true

server.port=${application.nosliw-static.port}
spring.application.name=${application.nosliw-static.name}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.config.import: configserver:http://localhost:8888

