spring.main.allow-circular-references = true

server.port=${application.nosliw-static.port}
spring.application.name=${application.nosliw-static.name}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.config.import: configserver:http://localhost:8888


# Disable HTTP caching for static resources (CSS, JS, Images)
spring.web.resources.cache.period=0
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

# Disable internal resource chain caching
spring.web.resources.chain.cache=false

# Disable template caching (if using Thymeleaf or FreeMarker)
spring.thymeleaf.cache=false
spring.freemarker.cache=false