spring.main.allow-circular-references = true
server.port=8081
spring.application.name=static
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

application.directory.temp = C:/Temp/nosliw/temp/