DROP TABLE IF EXISTS nosliw.DATATYPEDEF;
DROP TABLE IF EXISTS nosliw.DATAOPERATION;
DROP TABLE IF EXISTS nosliw.OPERATIONPARM;
DROP TABLE IF EXISTS nosliw.OPERATIONJS;


CREATE TABLE nosliw.DATATYPE(
	ID   				VARCHAR(20)			NOT NULL ,
	NAME				VARCHAR(20)			NOT NULL,
	
	VERSION				VARCHAR(20),
	VERSION_MAJOR		INT,
	VERSION_MINOR		INT,
	VERSION_REVISION	VARCHAR(20),
	
	DESCRIPTION			VARCHAR(20),
	
	PARENTINFO			VARCHAR(20),
	
	LINKEDVERSION		VARCHAR(20),

	PRIMARY KEY (ID)	
);

CREATE TABLE nosliw.DATATYPEPIC(
	ID   				VARCHAR(20)			NOT NULL,
	NAME				VARCHAR(20)			NOT NULL,
	
	VERSION				VARCHAR(20),
	VERSION_MAJOR		INT,
	VERSION_MINOR		INT,
	VERSION_REVISION	VARCHAR(20),
	
	DESCRIPTION			VARCHAR(20),
	
	PARENTINFO			VARCHAR(20),
	
	LINKEDVERSION		VARCHAR(20),

	NODES				VARCHAR(10000),
	
	PRIMARY KEY (ID)	
);


CREATE TABLE nosliw.DATAOPERATION(
	ID					 VARCHAR(20) 		NOT NULL,
	
	DATATYPENAME		 VARCHAR(20) 		NOT NULL,

	DATATYPEVERSION		 VARCHAR(20) 		NOT NULL,
	
	NAME				 VARCHAR(20)		NOT NULL,
	
	DESCRIPTION			VARCHAR(20),
	
	PRIMARY KEY (ID)	
	

);

CREATE TABLE nosliw.OPERATIONPARM(
	ID					 VARCHAR(20) 		NOT NULL,

	OPERATION			 VARCHAR(20) 		NOT NULL,
	
	TYPE				VARCHAR(20)			NOT NULL,
	
	NAME				 VARCHAR(20),
	
	DATATYPE			 VARCHAR(20) 		NOT NULL,

	DESCRIPTION			VARCHAR(20),
	
	PRIMARY KEY (ID)	
);

CREATE TABLE nosliw.OPERATIONJS(
	ID					VARCHAR(20)			NOT NULL,
	OPERATION			VARCHAR(20)			NOT NULL,
	SCRIPT				VARCHAR(2000)			NOT NULL,
	RESOURCES			VARCHAR(2000)			NOT NULL,
	
	PRIMARY KEY (ID)
);

