spring.main.allow-circular-references = true

datasource.data_source_url = http://localhost:8085/nosliw/datasource/
story.url = http://localhost:8083/nosliw/design/


division.manual.source_path = file:///C:/Mywork/CoreProjects/ApplicationData
division.manual.path = file:///C:Temp/nosliw/temp/manualbundleexport

division.story.path = file:///C:/Temp/nosliw/data/storydesign


uitag.path = file:///C:/Mywork/CoreProjects/ApplicationLib/uitag
codetable.path = file:///C:/Mywork/CoreProjects/ApplicationData/codetable
script.path = file:///C:/Mywork/CoreProjects/ApplicationData
configure.path = file:///C:/Mywork/CoreProjects/ApplicationData/configure
taskinterface.path = file:///C:/Mywork/CoreProjects/ApplicationData/serviceinterface

rhino.script_export_path = file:///C:/Temp/nosliw/temp/scriptexport/scripts

bundle.export_path = file:///C:/Temp/nosliw/temp/bundleexport
