spring.main.allow-circular-references = true

server.port=${application.nosliw-core.port}
spring.application.name=${application.nosliw-core.name}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.config.import: configserver:http://localhost:8888



division.manual.source_path = file:///C:/Mywork/CoreProjects/ApplicationData
division.manual.path = file:///C:Temp/nosliw/temp/manualbundleexport

uitag.path = file:///C:/Mywork/CoreProjects/ApplicationLib/uitag
codetable.path = file:///C:/Mywork/CoreProjects/ApplicationData/codetable
script.path = file:///C:/Mywork/CoreProjects/ApplicationData
configure.path = file:///C:/Mywork/CoreProjects/ApplicationData/configure
taskinterface.path = file:///C:/Mywork/CoreProjects/ApplicationData/serviceinterface

rhino.script_export_path = file:///C:/Temp/nosliw/temp/scriptexport/scripts

bundle.export_path = file:///C:/Temp/nosliw/temp/bundleexport
