spring.main.allow-circular-references = true

uitag.path = file:///C:/Mywork/CoreProjects/ApplicationLib/uitag

division.manual.source_path = file:///C:/Mywork/CoreProjects/ApplicationData
division.manual.path = file:///C:Temp/nosliw/temp/manualbundleexport

division.story.path = file:///C:/Temp/nosliw/data/storydesign

codetable.path = file:///C:/Mywork/CoreProjects/ApplicationData/codetable

script.path = file:///C:/Mywork/CoreProjects/ApplicationData/script
