spring.main.allow-circular-references = true
server.port=8083

# Database authentication credentials
spring.datasource.username=admin
spring.datasource.password=admin

# Optional: Spring Boot usually auto-detects this based on the URL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost/nosliw?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true

spring.application.name=story
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

datasource.data_source_url = http://datasource:8085/nosliw/datasource/
gateway.url_single = http://core:8080/nosliw/gatewaysingle

miniapp.url = http://localhost:8081/data/main/application/application.html

division.story.path = file:///C:/Temp/nosliw/data/storydesign
