spring.main.allow-circular-references = true
server.port=8083

uitag.path = file:///C:/Mywork/CoreProjects/ApplicationLib/uitag/

division.manual.source_path = file:///C:/Mywork/CoreProjects/ApplicationData/

division.story.path = file:///C:/Temp/nosliw/data/storydesign
