spring.main.allow-circular-references = true
server.port=8083

datasource.data_source_url = http://localhost:8085/nosliw/datasource/
gateway.url_single = http://localhost:8080/nosliw/gatewaysingle

miniapp.url = http://localhost:8081/data/main/application/application.html

division.story.path = file:///C:/Temp/nosliw/data/storydesign
division.story.gateway_url = http://localhost:8081/nosliw/gateway/

