package com.nosliw.core.application.brick;

import com.nosliw.common.utils.HAPConstantShared;
import com.nosliw.core.application.HAPIdBrickType;

public class HAPEnumBrickType {

	public static HAPIdBrickType MODULE_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_MODULE, "1.0.0");

	public static HAPIdBrickType WRAPPERBRICK_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_WRAPPERBRICK, "1.0.0");

	public static HAPIdBrickType TEST_COMPLEX_1_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_TEST_COMPLEX_1, "1.0.0");
	public static HAPIdBrickType TEST_COMPLEX_SCRIPT_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_TEST_COMPLEX_SCRIPT, "1.0.0");
	public static HAPIdBrickType TEST_COMPLEX_TASK_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_TEST_COMPLEX_TASK, "1.0.0");
	public static HAPIdBrickType TEST_COMPLEX_TASK_SCRIPT_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_TEST_COMPLEX_TASK_SCRIPT, "1.0.0");

	public static HAPIdBrickType TASK_TASK_SCRIPT_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_TASK_TASK_SCRIPT, "1.0.0");
	public static HAPIdBrickType TASK_EXPRESSION_SCRIPT_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_TASK_EXPRESSION_SCRIPT, "1.0.0");

	public static HAPIdBrickType TASK_TASK_FLOW_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_TASK_FLOW, "1.0.0");
	public static HAPIdBrickType TASK_TASK_ACTIVITYTASK_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_FLOW_ACTIVITYTASK, "1.0.0");
	public static HAPIdBrickType TASK_TASK_ACTIVITYDYNAMIC_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_FLOW_ACTIVITYDYNAMIC, "1.0.0");

	public static HAPIdBrickType TASKWRAPPER_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_TASKWRAPPER, "1.0.0");

	
	public static HAPIdBrickType DATAASSOCIATION_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_DATAASSOCIATION, "1.0.0");
	public static HAPIdBrickType DATAASSOCIATIONFORTASK_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_DATAASSOCIATIONFORTASK, "1.0.0");
	public static HAPIdBrickType DATAASSOCIATIONFOREXPRESSION_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_DATAASSOCIATIONFOREXPRESSION, "1.0.0");
	
	public static HAPIdBrickType CONTAINER_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_CONTAINER, "1.0.0");
	public static HAPIdBrickType CONTAINERLIST_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_CONTAINERLIST, "1.0.0");
	

	public static HAPIdBrickType INTERACTIVETASKINTERFACE_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_INTERACTIVETASKINTERFACE, "1.0.0");
	public static HAPIdBrickType INTERACTIVEEXPRESSIONINTERFACE_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_INTERACTIVEEXPRESSIONINTERFACE, "1.0.0");
	
	public static HAPIdBrickType SERVICEINTERFACE_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_SERVICEINTERFACE, "1.0.0");
	public static HAPIdBrickType SERVICEPROFILE_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_SERVICEPROFILE, "1.0.0");

	public static HAPIdBrickType SCRIPTEXPRESSIONLIB_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_SCRIPTEXPRESSIONLIB, "1.0.0");
	public static HAPIdBrickType SCRIPTEXPRESSIONLIBELEMENT_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_SCRIPTEXPRESSIONLIBELEMENT, "1.0.0");

	public static HAPIdBrickType SCRIPTEXPRESSIONGROUP_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_SCRIPTEXPRESSIONGROUP, "1.0.0");

	public static HAPIdBrickType TASKWRAPPERDATAEXPRESSION = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_TASKWRAPPERDATAEXPRESSION, "1.0.0");

	public static HAPIdBrickType DATAEXPRESSIONSTANDALONE_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_DATAEXPRESSIONSTANDALONE, "1.0.0");
	public static HAPIdBrickType DATAEXPRESSIONLIB_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_DATAEXPRESSIONLIB, "1.0.0");
	public static HAPIdBrickType DATAEXPRESSIONLIBELEMENT_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_DATAEXPRESSIONLIBELEMENT, "1.0.0");
	public static HAPIdBrickType DATAEXPRESSIONGROUP_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_DATAEXPRESSIONGROUP, "1.0.0");
	
	public static HAPIdBrickType SERVICEPROVIDER_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_SERVICEPROVIDER, "1.0.0");

	public static HAPIdBrickType DECORATIONSCRIPT_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_DECORATION_SCRIPT, "1.0.0");

	public static HAPIdBrickType DATA_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_DATA, "1.0.0");
	public static HAPIdBrickType VALUE_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_VALUE, "1.0.0");

	
	public static HAPIdBrickType UICONTENT_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_UICONTENT, "1.0.0");
	public static HAPIdBrickType UIPAGE_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_UIPAGE, "1.0.0");
	public static HAPIdBrickType UICUSTOMERTAG_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_UICUSTOMERTAG, "1.0.0");
	public static HAPIdBrickType UICUSTOMERTAGDEBUGGER_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_UICUSTOMERTAGDEBUGGER, "1.0.0");
	public static HAPIdBrickType UIWRAPPERCONTENTCUSTOMERTAGDEBUGGER_100 = new HAPIdBrickType(HAPConstantShared.RUNTIME_RESOURCE_TYPE_UIWRAPPERCONTENTCUSTOMERTAGDEBUGGER, "1.0.0");

}
